[phases.setup]
nixPkgs = ["nodejs_22", "yarn-1_x", "openssl", "curl", "wget"]
nixLibs = ["gcc-unwrapped", "libuuid", "libGL"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn run build"]

[start]
cmd = "yarn run start"

