'use client';

import React from 'react';

interface InvoiceData {
  saleType: 'Retail' | 'Trade' | 'Commercial';
  // Add other necessary fields as needed
}

interface InvoiceThirdPageProps {
  invoiceData: InvoiceData;
  fontSize?: number;
  padding?: number;
}

export const InvoiceThirdPage: React.FC<InvoiceThirdPageProps> = ({ 
  invoiceData, 
  fontSize = 10, 
  padding = 8 
}) => {
  // Don't show terms and conditions for Trade invoices
  const shouldShowTerms = invoiceData.saleType !== 'Trade';

  if (!shouldShowTerms) {
    return null;
  }

  const pageStyles = {
    container: {
      fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: `${fontSize}px`,
      color: '#141414',
      backgroundColor: '#ffffff',
      paddingTop: '50px',
      paddingBottom: '50px',
      paddingLeft: '30px',
      paddingRight: '30px',
      minHeight: '297mm', // A4 height
      pageBreakBefore: 'always' as const,
      pageBreakInside: 'avoid' as const
    },
    headerSection: {
      paddingTop: '5px',
      paddingBottom: '0px',
      paddingLeft: '0px',
      paddingRight: '0px',
      backgroundColor: 'rgb(232, 232, 232)',
      textAlign: 'center' as const,
      marginTop: '0px',
      marginBottom: '15px',
      marginLeft: '0px',
      marginRight: '0px'
    },
    termsContent: {
      paddingTop: '0px',
      paddingBottom: '0px',
      paddingLeft: '0px',
      paddingRight: '0px',
      backgroundColor: 'rgba(0, 0, 0, 0)',
      textAlign: 'start' as const,
      marginTop: '0px',
      marginBottom: '0px',
      marginLeft: '0px',
      marginRight: '0px'
    }
  };

  const termsAndConditionsHTML = `
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">1. The Agreement </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">1.1. These terms constitute the fundamental agreement between Bluebell Motorhouse Limited and Customer and can be modified only in writing. If any term is unenforceable, the rest remain valid. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">1.2. Sales Disclaimers and Checklist provided or shared during the sale are also to be considered as part of the contract. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">1.3. Warranty  terms  and conditions or disclaimers provided as part of a warranty, invoice or sales documentation are also to be considered part of the contract. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">2. Orders and Delivery: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">2.1. Orders are subject to written confirmation or confirmation of receipt of payment by the Bluebell Motorhouse Limited </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">2.2. Delivery dates are estimates, not guaranteed. Bluebell Motorhouse Limited is not liable for delays beyond its control. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">2.3. Delivery occurs at the Bluebell Motorhouse Limited premises unless agreed otherwise. <br>2.4. Delivery costs are non-refundable unless agreed by Bluebell Motorhouse Limited. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3. Vehicle Sales, Retail / Consumer: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.1. Vehicles are sold as roadworthy at delivery. Statutory rights under the Consumer Rights Act 2015 apply. <br>3.2. Returned vehicles where no fault is present will inclur a £250 charge to cover relisting and administrative costs in addition to a deduction to cover the cost of any warranty, before any reductions / discounts.</span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.3. Used vehicles include the Consumer Rights Act provisions against major defects at the time of sale, unless stated at time of sale or amended by the checklist. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.4. Customers must inspect vehicles before purchase. Statutory quality and fitness conditions do not cover defects revealed by inspection or disclosed defects. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.5. Any defect or issue highlighted at the time of sale will fall outside of the remit of the warranty and liability coverage, unless agreed in writing. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.6. Title for goods sold passes upon full payment; vehicles remain Dealer property until paid. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.7. Within 30 days of delivery, consumers may reject faulty vehicles under the Consumer Rights Act 2015, proving the fault existed at purchase and was not disclosed or the sale was not agreed with the faults being taken into consideration and the price adjusted accordingly.  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.8. Vehicles must be returned within 48 hours or at a time agreed by Bluebell Motorhouse Limited. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.9. Items unchecked or identified as requiring attention in the Checklist provided at the time of sale are outside of the scope of the Consumer Rights Act. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.10. Between 30 days and 6 months, Bluebell Motorhouse Limited may repair faults instead of accepting rejection. Bluebell Motorhouse Limited will not be responsible for any repairs or their costs to the vehicle carried out by third parties unless pre-agreed in writing. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.11. Returns incurring excess mileage may be charged at 50p per mile. Damaged returns may incur repair costs. Excess mileage is anything over 200 miles per week from the time of sale. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">3.12. Returned vehicles must be washed and valeted prior to their return to Bluebell Motorhouse Limited. Any vehicles not washed and/or valeted may incur a £100 deduction to cover these costs. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">4. Vehicle Sales, Trade: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">4.1. Trade sales are accompanied with their own sales terms which take priority over all other terms and conditions or disclaimers. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">4.2. Trade-Sales, clearly communicated as Trade-Sales at the point of sale, are outside of the scope of the Consumer Protection provisions. 4.3. Therefore, no warranty or post-sale liabilities will apply.   </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">4.4. Customers are able to obtain their own third-party warranty for Trade vehicles. These are not sold or covered by Bluebell Motorhouse Limited. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">5. Part Exchange: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">5.1. Part-exchanged vehicles must be owned by the Customer, free of encumbrances, or subject to settleable finance, with allowances adjusted accordingly. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">5.2. Vehicles must match the Customer's declared condition, mileage, and history. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">5.3. Once a part exchange has been agreed and completed, any refund will be subject to the availability of the vehicle taken in part exchange. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">5.4. Where part exchanged vehicles are no longer available due to onward sale, the refund amount will be based on the sale price inclusive of the value attributed to the part exchanged vehicle. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">6. Payment and Deposits: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">6.1. Full payment is due upon notification of vehicle availability. Payment must be by bank transfer or a method pre-agreed. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">6.2. Deposits are non-refundable if the Customer cancels, except where Bluebell Motorhouse Limited cannot deliver as agreed. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">6.3. Deposits paid will be deducted from the sale price at sale completion. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7. Cancellations and Returns: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.1. Customers may cancel before delivery with written notice. Refunds, excluding deposits, are processed within 14 days. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.2. For distance sales, consumers have 14 days post-delivery to return vehicles in original condition, bearing return costs unless faulty (Consumer Contracts Regulations 2013) and minus any deductions as specified in the sales documentation. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.3.. If cancelled after ordering extras, the Customer may be charged for those costs. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.4. If the Customer fails to collect within 14 days of notification, Bluebell Motorhouse Limited may cancel, sell the vehicle, and deduct resale losses from the funds paid in addition to deposits. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.5. Any refund agreed will be minus any damage charged to the customer including physical/cosmetic damage or faults or drive-on damage.  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.6. Excessive mileage will be charged at 0.50p per mile (any mileage beyond 200 miles per week is considered excessive) and be deducted from any refund. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">7.7. Customers may be required to have the car valeted prior to return for vehicles considered hazardous or excessively dirty. Failure to do so may incur a deduction of £100 to cover a valet, at the discretion of Bluebell Motorhouse Limited. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8. Liability: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.1. Bluebell Motorhouse Limited is liable only for loss or damage caused by its negligence. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.2. Liability is limited to repair, replacement, or refund, excluding indirect losses (e.g., loss of use). </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.3. Customers are responsible for items left in vehicles. Any items left in a vehicle on its return to Bluebell Motorhouse Limited will be disposed of, unless pre-agreed.  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.4. Customers' are responsible for ensuring nothing that may cause direct or undirect harm to Bluebell Motorhouse Limited, its staff or customers is left in vehicles </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.5. Statutory rights for death, injury, or fraud are unaffected.</span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.6. Where a vehicle has been repaired by a thiord party without prior written agreement from Bluebell Motorhouse Limited, Bluebell Motorhouse Limited will not be responsible for the cost of any such unauthorised repairs.  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">8.7. Repairs stated in 8.6. may invalidate any warranty and regulatory responsibility due to the vehicle being altered and/or modified. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">9. Force Majeure: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">9.1. The Dealer is not liable for delays or failures due to events beyond its control, including natural disasters, strikes, or supply issues. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">10. Warranty: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">10.1. New vehicles carry manufacturer warranties; used vehicles have a warranty as agreed at time of sale, unless specified explicitly. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">10.2. No warranty applies for commercial use, business-to-business sales, or modified vehicles. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">10.3. Where warranty rights are exercised, Bluebell Motorhouse Limited will not be responsible for the communication or repair of any vehicles by third parties, unless agreed in writing. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">10.4. All warranty terms and conditions are express terms of the sale and are binding.  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11. Disputes: </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.1. Contact aftersales@Bluebellmotorhouse.co.uk with any issues or complaints. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.2. Acknowledgement to issues raised will be provided within 48 working hours. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.3. Issues will be resolved within 14 days where possible, with any delays being communicated. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.4. Unresolved issues may be referred to the Motor Ombudsman (www.themotorombudsman.org) or the English courts. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.5. Bluebell Motorhouse Limited will not be responsible for any third-party repairs or work carried out. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">11.6. Such work, if resulting in any modification/alteration of the vehicle including taking apart components, will be considered as voiding the warranty and a rejection of the right to repair provided by Bluebell Motorhouse Limited unless prior agreed in writing. <br>12. Data Protection </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">12.1. The Dealer processes personal data in accordance with UK GDPR protocols for sales, services, and marketing (with consent).  </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;">12.2. Data may be shared with finance providers or as required by law. </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><span style="font-size: 6.5pt; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;"> </span></p>
    <p class="MsoNormal" style="margin: 0cm; font-size: medium; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; background-image: none; background-position: 0% 0%; background-size: auto; background-repeat: repeat; background-attachment: scroll; background-origin: padding-box; background-clip: border-box;"><strong><span style="font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;"><span style="font-size: 6.5pt;">Bluebell Motorhouse Limited, Unit 3, Spencer Business Centre, Factory St, Bradford BD4 9NW. Last updated May 2025.</span></span></strong></p>
  `;

  return (
    <div style={pageStyles.container}>
      {/* Header Section */}
      <div style={pageStyles.headerSection}>
        <strong>BLUEBELL MOTORHOUSE STANDARD LIMITED TERMS AND CONDITIONS</strong>
      </div>

      {/* Terms and Conditions Content */}
      <div 
        style={pageStyles.termsContent}
        dangerouslySetInnerHTML={{ __html: termsAndConditionsHTML }}
      />
    </div>
  );
};

export default InvoiceThirdPage;
